---

- name: Disable official RabbitMQ repository on all
  ansible.builtin.set_fact:
    rabbitmq_repo_state: "absent"

- name: Enable official RabbitMQ repository on older debian
  ansible.builtin.set_fact:
    rabbitmq_repo_state: "present"
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_version is version('10', '<')

- name: Create apt keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  when: rabbitmq_repo_state == "present"

- name: Import RabbitMQ packaging GPG signing key
  ansible.builtin.apt_key:
    id: "{{ rabbitmq_apt_key_fingerprint }}"
    url: "https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/gpg.9F4587F226208342.key"
    keyring: /etc/apt/keyrings/rabbitmq.gpg
    state: "present"
  when: rabbitmq_repo_state == "present"

- name: Import RabbitMQ-Erlang packaging GPG signing key
  ansible.builtin.apt_key:
    id: "{{ rabbitmq_erlang_apt_key_fingerprint }}"
    url: "https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/gpg.E495BB49CC4BBE5B.key"
    keyring: /etc/apt/keyrings/rabbitmq-erlang.gpg
    state: "present"
  when: rabbitmq_repo_state == "present"

- name: Remove old RabbitMQ apt repository entry
  ansible.builtin.apt_repository:
    repo: >-
      deb [signed-by=/usr/share/keyrings/rabbitmq.gpg]
      https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/deb/{{ ansible_distribution | lower }}
      {{ ansible_distribution_release }} main
    filename: rabbitmq
    update_cache: no
    state: absent

- name: Remove old RabbitMQ-Erlang apt repository entry
  ansible.builtin.apt_repository:
    repo: >-
      deb [signed-by=/usr/share/keyrings/rabbitmq-erlang.gpg]
      https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/deb/{{ ansible_distribution | lower }}
      {{ ansible_distribution_release }} main
    filename: rabbitmq-erlang
    update_cache: no
    state: absent

- name: Remove old RabbitMQ apt repository files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apt/sources.list.d/dl_bintray_com_rabbitmq_debian.list
    - /etc/apt/sources.list.d/dl_bintray_com_rabbitmq_erlang_debian.list
    - /etc/apt/sources.list.d/dl_cloudsmith_io_public_rabbitmq_rabbitmq_server_deb_{{ ansible_distribution | lower }}.list
    - /etc/apt/sources.list.d/dl_cloudsmith_io_public_rabbitmq_rabbitmq_erlang_deb_{{ ansible_distribution | lower }}.list
    - /usr/share/keyrings/rabbitmq.gpg
    - /usr/share/keyrings/rabbitmq-erlang.gpg

- name: Remove old packaging GPG signing keys
  ansible.builtin.apt_key:
    id: "{{ item }}"
    state: "absent"
    keyring: /etc/apt/trusted.gpg
  loop:
    - "{{ erlang_apt_key_fingerprint }}"
    - "{{ old_rabbitmq_apt_key_fingerprint }}"
    - "{{ bintray_rabbitmq_apt_key_fingerprint }}"
    - "{{ rabbitmq_apt_key_fingerprint }}"
    - "{{ rabbitmq_erlang_apt_key_fingerprint }}"

- name: Add or remove RabbitMQ repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [signed-by=/etc/apt/keyrings/rabbitmq.gpg]
      https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/deb/{{ ansible_distribution | lower }}
      {{ ansible_distribution_release }} main
    filename: rabbitmq
    state: "{{ rabbitmq_repo_state }}"

- name: Add or remove RabbitMQ-Erlang repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [signed-by=/etc/apt/keyrings/rabbitmq-erlang.gpg]
      https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/deb/{{ ansible_distribution | lower }}
      {{ ansible_distribution_release }} main
    filename: rabbitmq-erlang
    state: "{{ rabbitmq_repo_state }}"

- name: Remove RabbitMQ packaging GPG signing key files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apt/keyrings/rabbitmq.gpg
    - /etc/apt/keyrings/rabbitmq-erlang.gpg
  when: rabbitmq_repo_state == "absent"

- name: Install RabbitMQ packages
  ansible.builtin.apt:
    name: rabbitmq-server
    state: present
