---

- name: Disable official RabbitMQ repository on all
  set_fact:
    rabbitmq_repo_state: "absent"

- name: Enable official RabbitMQ repository on older debian
  set_fact:
    rabbitmq_repo_state: "present"
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_version is version('10', '<')

- name: Import RabbitMQ packaging GPG signing key
  apt_key:
    id: "{{ rabbitmq_apt_key_fingerprint }}"
    url: "https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc"
    state: "present"
  when: rabbitmq_repo_state == "present"

- name: Remove old packaging GPG signing keys
  apt_key:
    id: "{{ item }}"
    state: "absent"
  with_items:
    - "{{ erlang_apt_key_fingerprint }}"
    - "{{ old_rabbitmq_apt_key_fingerprint }}"

- name: Add or remove RabbitMQ repository
  apt_repository:
    repo: "deb https://dl.bintray.com/rabbitmq/debian {{ ansible_distribution_release }} main"
    state: "{{ rabbitmq_repo_state }}"

- name: Add or remove RabbitMQ-Erlang repository
  apt_repository:
    repo: "deb http://dl.bintray.com/rabbitmq-erlang/debian {{ ansible_distribution_release }} erlang-21.x"
    state: "{{ rabbitmq_repo_state }}"

- name: Delete RabbitMQ packaging GPG signing key
  apt_key:
    id: "{{ rabbitmq_apt_key_fingerprint }}"
    url: "https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc"
    state: "absent"
  when: rabbitmq_repo_state == "absent"

- name: Install RabbitMQ packages
  apt:
    name: rabbitmq-server
    state: present

- name: Install monitoring shell script
  template:
    src: monitoring/monitor-rabbitmq-queues
    dest: /usr/local/bin/monitor-rabbitmq-queues
    mode: "u=rwx,g=r,o=r"
    owner: "root"
    group: "root"

- name: Install monitoring cron fragment
  template:
    src: monitoring/cron
    dest: /etc/cron.d/monitor-rabbitmq-queues
    mode: "u=rw,g=r,o=r"
    owner: "root"
    group: "root"
