---
- name: Import RabbitMQ packaging GPG signing key
  apt_key:
    url: https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc
    state: present

- name: Add RabbitMQ repository
  apt_repository:
    repo: "deb https://dl.bintray.com/rabbitmq/debian {{ansible_distribution_release}} main erlang"
    state: present

- name: Pin Erlang packages to known good version
  template:
    src: "templates/erlang.pref"
    dest: "/etc/apt/preferences.d/erlang.pref"

- name: Pin RabbitMQ packages to known good version
  template:
    src: "templates/rabbitmq.pref"
    dest: "/etc/apt/preferences.d/rabbitmq.pref"

- name: Install RabbitMQ packages
  apt:
    name: rabbitmq-server
    state: present
